networks:
  grafana-network:
    external: true
  traefik-network:
    external: true

volumes:
  grafana-data:
  grafana-postgres:
  grafana-postgres-backup:
  grafana-data-backups:
  grafana-database-backups:
  traefik-certificates:

services:
  postgres:
    image: ${GRAFANA_POSTGRES_IMAGE_TAG}
    volumes:
      - grafana-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${GRAFANA_DB_NAME}
      POSTGRES_USER: ${GRAFANA_DB_USER}
      POSTGRES_PASSWORD: ${GRAFANA_DB_PASSWORD}
    networks:
      - grafana-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${GRAFANA_DB_NAME}", "-U", "${GRAFANA_DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  grafana:
    image: ${GRAFANA_IMAGE_TAG}
    volumes:
      - grafana-data:${DATA_PATH}
    environment:
      GF_DATABASE_TYPE: ${GRAFANA_DB_TYPE}
      GF_DATABASE_HOST: postgres
      GF_DATABASE_NAME: ${GRAFANA_DB_NAME}
      GF_DATABASE_USER: ${GRAFANA_DB_USER}
      GF_DATABASE_PASSWORD: ${GRAFANA_DB_PASSWORD}
      GF_SERVER_DOMAIN: ${GRAFANA_HOSTNAME}
      GF_SERVER_ROOT_URL: ${GRAFANA_URL}
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USERNAME}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_AUTH_ANONYMOUS_ENABLED: ${GRAFANA_AUTH_ANONYMOUS_ENABLED}
      GF_AUTH_ANONYMOUS_DISABLE_LOGIN_FORM: ${GRAFANA_AUTH_ANONYMOUS_DISABLE_LOGIN_FORM}
      GF_USERS_ALLOW_SIGN_UP: ${GRAFANA_USERS_ALLOW_SIGN_UP}
      GF_PATHS_PROVISIONING: ${GRAFANA_PROVISIONING_PATH}
      GF_PATHS_CONFIG: ${GRAFANA_CONFIG_PATH}
      GF_PATHS_DATA: ${GRAFANA_DATA_PATH}
      GF_PATHS_LOGS: ${GRAFANA_LOGS_PATH}
      GF_PATHS_PLUGINS: ${GRAFANA_PLUGINS_PATH}
      GF_INSTALL_PLUGINS: ${GRAFANA_PLUGINS_INSTALL}
      GF_SMTP_ENABLED: 'true'
      GF_SMTP_HOST: ${GRAFANA_SMTP_ADDRESS}:${GRAFANA_SMTP_PORT}
      GF_SMTP_USER: ${GRAFANA_SMTP_USER_NAME}
      GF_SMTP_PASSWORD: ${GRAFANA_SMTP_PASSWORD}
      GF_SMTP_FROM_NAME: ${GRAFANA_SMTP_NAME_FROM}
      GF_SMTP_FROM_ADDRESS: ${GRAFANA_EMAIL_FROM}
    networks:
      - grafana-network
      - traefik-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"
      # Match incoming requests on a specific hostname
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOSTNAME}`)"
      # Assign the router to a named Traefik service
      - "traefik.http.routers.grafana.service=grafana"
      # Use the 'websecure' (HTTPS) entry point
      - "traefik.http.routers.grafana.entrypoints=websecure"
      # Define the internal container port for routing
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      # Enable TLS on this router
      - "traefik.http.routers.grafana.tls=true"
      # Use Let's Encrypt for certificate management
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      # Pass the original Host header to the container
      - "traefik.http.services.grafana.loadbalancer.passhostheader=true"
      # Apply a compression middleware
      - "traefik.http.routers.grafana.middlewares=compresstraefik"
      # Define settings for the compression middleware
      - "traefik.http.middlewares.compresstraefik.compress=true"
      # Specify which Docker network Traefik should use for routing
      - "traefik.docker.network=traefik-network"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      traefik:
        condition: service_healthy

  traefik:
    image: ${TRAEFIK_IMAGE_TAG}
    command:
      # Set the log level (DEBUG, INFO, WARN, ERROR)
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      # Enable the built-in API and web-based dashboard
      - "--api.dashboard=true"
      # Enable the /ping endpoint so we can health-check Traefik
      - "--ping=true"
      # Assign the /ping endpoint to a dedicated entry point on port 8082
      - "--ping.entrypoint=ping"
      - "--entrypoints.ping.address=:8082"
      # Define the primary HTTP entry point on port 80
      - "--entrypoints.web.address=:80"
      # Define the secure (HTTPS) entry point on port 443
      - "--entrypoints.websecure.address=:443"
      # Enable the Docker provider to detect containers and their labels
      - "--providers.docker=true"
      # Point Traefik to the Docker socket
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      # Prevent automatic exposure of all containers; only expose containers
      # with "traefik.enable=true"
      - "--providers.docker.exposedbydefault=false"
      # Use ACME (Let's Encrypt) to generate/renew certificates via TLS challenge
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      # The email address used by Let's Encrypt for renewal notices
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      # The file where ACME certificates are stored inside the container
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      # Enable Prometheus metrics
      - "--metrics.prometheus=true"
      # Configure Prometheus histogram buckets
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      # Check for newer Traefik versions and optionally log that info
      - "--global.checknewversion=true"
      # Disable sending anonymous usage data to the Traefik maintainers
      - "--global.sendanonymoususage=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certificates:/etc/traefik/acme
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping","--spider"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"
      # A router to expose the Traefik dashboard
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      # Basic Authentication for the Traefik dashboard
      - "traefik.http.routers.dashboard.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      # Specify the internal server port to the dashboard service
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      # Pass the original Host header to the backend
      - "traefik.http.services.dashboard.loadbalancer.passhostheader=true"
      # HTTP -> HTTPS redirect for all hosts
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped

  backups:
    image: ${GRAFANA_POSTGRES_IMAGE_TAG}
    command: >-
      sh -c 'sleep $BACKUP_INIT_SLEEP &&
      while true; do
        pg_dump -h postgres -p 5432 -d $GRAFANA_DB_NAME -U $GRAFANA_DB_USER | gzip > $POSTGRES_BACKUPS_PATH/$POSTGRES_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").gz &&
        tar -zcpf $DATA_BACKUPS_PATH/$DATA_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").tar.gz $DATA_PATH &&
        find $POSTGRES_BACKUPS_PATH -type f -mtime +$POSTGRES_BACKUP_PRUNE_DAYS | xargs rm -f &&
        find $DATA_BACKUPS_PATH -type f -mtime +$DATA_BACKUP_PRUNE_DAYS | xargs rm -f;
        sleep $BACKUP_INTERVAL; done'
    volumes:
      - grafana-postgres-backup:/var/lib/postgresql/data
      - grafana-data:${DATA_PATH}
      - grafana-data-backups:${DATA_BACKUPS_PATH}
      - grafana-database-backups:${POSTGRES_BACKUPS_PATH}
    environment:
      GRAFANA_DB_NAME: ${GRAFANA_DB_NAME}
      GRAFANA_DB_USER: ${GRAFANA_DB_USER}
      PGPASSWORD: ${GRAFANA_DB_PASSWORD}
      BACKUP_INIT_SLEEP: ${BACKUP_INIT_SLEEP}
      BACKUP_INTERVAL: ${BACKUP_INTERVAL}
      POSTGRES_BACKUP_PRUNE_DAYS: ${POSTGRES_BACKUP_PRUNE_DAYS}
      DATA_BACKUP_PRUNE_DAYS: ${DATA_BACKUP_PRUNE_DAYS}
      POSTGRES_BACKUPS_PATH: ${POSTGRES_BACKUPS_PATH}
      DATA_BACKUPS_PATH: ${DATA_BACKUPS_PATH}
      DATA_PATH: ${DATA_PATH}
      POSTGRES_BACKUP_NAME: ${POSTGRES_BACKUP_NAME}
      DATA_BACKUP_NAME: ${DATA_BACKUP_NAME}
    networks:
      - grafana-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
